{
  "openapi": "3.0.0",
  "info": {
    "title": "Palace Internal API",
    "version": "1.0.0",
    "description": "Titan, Bungees, AudioServer, Core"
  },
  "servers": [
    {
      "url": "https://internal-api.palace.network"
    }
  ],
  "paths": {
    "/titan/auth/login": {
      "post": {
        "description": "Login user to application",
        "tags": [
          "titan-auth"
        ],
        "requestBody": {
          "description": "login body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserSchema"
              },
              "example": {
                "username": "Legobuilder0813",
                "password": "S3cureP@ssw0rd"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "user successfuly logged in",
            "headers": {
              "Authorization": {
                "schema": {
                  "type": "string"
                },
                "description": "JWT token"
              }
            },
            "content": {
              "appication/json": {
                "example": {
                  "message": "Login Success!"
                }
              }
            }
          },
          "401": {
            "description": "Not logged in, invalid credentials",
            "content": {
              "application/json": {
                "example": {
                  "message": "Invalid credentials"
                }
              }
            }
          }
        }
      }
    },
    "/titan/auth/logout": {
      "post": {
        "description": "Logout from application",
        "tags": [
          "titan-auth"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "description": "logout body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserSchema"
              },
              "example": {
                "uuid": "9ab3b4c4-71d8-47c9-9e7d-adf040c53d2b"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "user successfuly logged out",
            "content": {
              "appication/json": {
                "example": {
                  "message": "Logout Success!"
                }
              }
            }
          },
          "401": {
            "description": "Not logged out, invalid credentials",
            "content": {
              "application/json": {
                "example": {
                  "message": "Invalid credentials"
                }
              }
            }
          }
        }
      }
    },
    "/titan/auth/user": {
      "get": {
        "description": "Get authenticated user",
        "tags": [
          "titan-auth"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "return authenticated user",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "user": {
                    "uuid": "9ab3b4c4-71d8-47c9-9e7d-adf040c53d2b",
                    "username": "Legobuilder0813",
                    "rank": "director",
                    "rank_tags": []
                  }
                }
              }
            }
          }
        }
      }
    },
    "/minecraft/server/online": {
      "get": {
        "description": "Get number of players online",
        "tags": [
          "minecraft-server"
        ],
        "responses": {
          "200": {
            "description": "returns current player count",
            "content": {
              "application/json": {
                "example": {
                  "server_is_online": {
                    "online": true,
                    "players": 100,
                    "maxPlayers": 2000
                  },
                  "server_is_offline": {
                    "online": false
                  }
                }
              }
            }
          }
        }
      }
    },
    "/minecraft/packs/list": {
      "get": {
        "description": "Get all configured resource packs",
        "tags": [
          "minecraft-packs"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "returns array of packs",
            "content": {
              "application/json": {
                "example": {
                  "packs": [
                    {
                      "name": "WDW",
                      "versions": [
                        {
                          "id": 340,
                          "url": "https://packs.palace.network/?p=wdw_1_12",
                          "hash": "a52009079f83673ee85202a172aed1712da96a84"
                        },
                        {
                          "id": 404,
                          "url": "https://packs.palace.network/?p=wdw_1_13",
                          "hash": "b43115b846853bb65b08e200cfe560f7a2188d4d"
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/minecraft/packs/get": {
      "get": {
        "description": "Get all configured resource packs",
        "tags": [
          "minecraft-packs"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "description": "the name of the pack",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "version",
            "description": "the version of the pack",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns array of packs",
            "content": {
              "application/json": {
                "example": {
                  "packs": [
                    {
                      "name": "WDW",
                      "versions": [
                        {
                          "id": 340,
                          "url": "https://packs.palace.network/?p=wdw_1_12",
                          "hash": "a52009079f83673ee85202a172aed1712da96a84"
                        },
                        {
                          "id": 404,
                          "url": "https://packs.palace.network/?p=wdw_1_13",
                          "hash": "b43115b846853bb65b08e200cfe560f7a2188d4d"
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/minecraft/chat/analyze": {
      "post": {
        "description": "Analyze a chat message for inappropriate text, links, etc.",
        "tags": [
          "minecraft-chat"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "description": "chat body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {},
              "example": {
                "uuid": "9ab3b4c4-71d8-47c9-9e7d-adf040c53d2b",
                "rank": "owner",
                "message": "Hello world!",
                "server": "Creative"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "response of analysis",
            "content": {
              "application/json": {
                "example": {
                  "valid_message": {
                    "success": true,
                    "uuid": "9ab3b4c4-71d8-47c9-9e7d-adf040c53d2b",
                    "message": "This is the original message sent",
                    "okay": true
                  },
                  "invalid_message": {
                    "success": true,
                    "uuid": "9ab3b4c4-71d8-47c9-9e7d-adf040c53d2b",
                    "message": "This is the original message sent",
                    "okay": false,
                    "filter_caught": "link sharing",
                    "offending_text": "www.google.com"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/minecraft/chat/log": {
      "post": {
        "description": "Log a chat message",
        "tags": [
          "minecraft-chat"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "description": "chat body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {},
              "example": {
                "uuid": "9ab3b4c4-71d8-47c9-9e7d-adf040c53d2b",
                "message": "Hello world!"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "response body",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          }
        }
      }
    },
    "/discord/link": {
      "post": {
        "description": "Link a Discord account to an MC account",
        "tags": [
          "discord"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "description": "request body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {},
              "example": {
                "minecraftUUID": "9ab3b4c4-71d8-47c9-9e7d-adf040c53d2b",
                "discordTag": "Legobuilder0813#6604",
                "acceptChannelLink": "https://discord.com/channels/245348983990386688/722112393202761818"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "success, along with linking pin and ms until that pin expires",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "pin": "382956",
                  "expires": 300000
                }
              }
            }
          },
          "403": {
            "description": "already linked MC",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Your Minecraft account is already linked to a Discord account!"
                }
              }
            }
          }
        }
      }
    },
    "/discord/unlink": {
      "post": {
        "description": "Unlink a Discord account from a Minecraft account",
        "tags": [
          "discord"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "description": "request body",
          "required": true,
          "content": {
            "application/json": {
              "schema": {},
              "example": {
                "minecraftUUID": "9ab3b4c4-71d8-47c9-9e7d-adf040c53d2b"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Discord account unlinked successfully",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          },
          "403": {
            "description": "No linked Discord account",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "There is no Discord account linked to this Minecraft account!"
                }
              }
            }
          }
        }
      }
    },
    "/discord/sync": {
      "post": {
        "description": "Sync a Discord account's display role with the linked Minecraft account's rank",
        "tags": [
          "discord"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "description": "request body",
          "required": true,
          "content":{
            "application/json": {
              "schema": {},
              "example": {
                "minecraftUUID": "9ab3b4c4-71d8-47c9-9e7d-adf040c53d2b"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Sync successful",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          },
          "400": {
            "description": "Sync unsuccessful (several causes)",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "This Minecraft account doesn't have a linked Discord account"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UserSchema": {
        "required": [
          "username",
          "password"
        ],
        "properties": {
          "uuid": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "tokens": {
            "type": "array"
          }
        }
      },
      "Error": {
        "type": "object",
        "required": [
          "status",
          "message"
        ],
        "properties": {
          "status": {
            "type": "integer",
            "description": "HTTP status code",
            "example": 200
          },
          "message": {
            "type": "string",
            "description": "Error description",
            "example": "Unknown player UUID"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "tags": []
}
